# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7808e08ca461d6390dcc6c196c20b3ea5e2744c9281d3a5551f412ca7b77b5d677e0824d540919d8456e739051c9fc14feda64b49d741a0c15c27f8071801272

test:
  secret_key_base: 6c2ca7726bc368f428b39573dd378ad171f65325f921180583000cd9617bc6f7fe423321f432f74306742edc871179c2ec56a2a82927c82b44f8db81a57120a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
